message: "Hello CloudBay Developer!"
io:
  crowdcode:
    greeting:
      welcome-message: "Welcome To The Greeting Service!"
      goodbye-message: "Goodbye From The Greeting Service!"
    services:
      time:    
        url: "http://localhost:8400/time-service/now"
      greeting:
        goodbye-url: "http://localhost:8300/greeting-service/sayGoodBye"
        welcome-url: "http://localhost:8300/greeting-service/sayHello"
      
spring:
  boot:
    admin:
      client:
        url: http://localhost:9091

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

