message: "hello tomorrow"
io:
  crowdcode:
    greeting:
      welcome-message: "Greetings From The Config Server! - TEST"
spring:
  boot:
    admin:
      client:
        url: http://localhost:9091
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
